
AUDIO_ENABLE               = no  # Audio output on port C6
AUTO_SHIFT_ENABLE = no
AUTO_SHIFT_MODIFIERS = no
BACKLIGHT_ENABLE           = no  # Enable keyboard backlight functionality
BLUETOOTH_ENABLE           = no  # Enable Bluetooth with the Adafruit EZ-Key HID
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE           = no  # Virtual DIP switch configuration(+1000)
COMBO_ENABLE = no
COMMAND_ENABLE             = no  # Commands for debug and configuration
CONSOLE_ENABLE             = no  # Console for debug(+400)
ENCODER_ENABLE = no
EXTRAKEY_ENABLE            = no # Audio control and System control(+450)
HAPTIC_ENABLE = no
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE                = no  # MIDI controls
MOUSEKEY_ENABLE            = no  # Mouse keys(+4700)
NKRO_ENABLE                = no # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
OLED_DRIVER_ENABLE = yes
POINTING_DEVICE_ENABLE = no
RGB_MATRIX_ENABLE = WS2812
RGBLIGHT_ENABLE            = no  # Enable WS2812 RGB underlight.
SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
STENO_ENABLE = no
SWAP_HANDS_ENABLE          = no  # Enable one-hand typing
TERMINAL_ENABLE = no
UCIS_ENABLE = no
UNICODE_ENABLE = no
